name: iitchs_base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-mp=3.1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cppad=20210000.6
  - gmp=6.2.1
  - ipopt=3.14.2
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.17
  - libstdcxx-ng=9.3.0
  - metis=5.1.0
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.2.2
  - pyscipopt
  - python=3.8.11
  - python_abi=3.8
  - readline=8.1
  - scip=7.0.3
  - scotch=6.0.9
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tbb=2020.2
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - amply==0.1.4
    - antlr4-python3-runtime==4.8
    - cycler==0.10.0
    - decorator==5.0.9
    - docutils==0.16
    - sphinx
    - sphinx-rtd-theme
    - myst-parser
    - gurobipy==9.1.2
    - kiwisolver==1.3.1
    - matplotlib>=3.4.3
    - multimethods==1.0.0
    - networkx==1.11
    - numpy==1.21.1
    - pandas==1.3.1
    - git+ssh://git@github.mit.edu/iitchs/pp3#egg=pp
    - pulp==2.4
    - pycddlib==2.1.4
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - scipy==1.7.1
    - shapely==1.7.1
    - simplekml==1.3.5
    - six==1.16.0
    - z3-solver==4.8.8.0
    - git+ssh://git@github.com/uqfoundation/pathos
    - pytest
